WebMMO.WEB/Areas/SshManage/Controllers/ManageSSHController.cs
using WebMMO.Core.DomainModels.SSH;
using WebMMO.Core.MessageResponse;
using WebMMO.Web.Areas.SshManage.Models;
using WebMMO.Web.Controllers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace WebMMO.Web.Areas.SshManage.Controllers
{
    public class ManageSSHController : BaseController
    {
        // GET: SshManage/ManageSSH
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult ManageSSHSearch(int draw = 1, int start = 0, int length = 10)
        {
            var tableParams = new FilterTableParams(Request, start, length, draw);
            var result = RepositoryService.SSHSystemService.SearchSSHSystem(tableParams);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ImportSSH()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ImportSSH(SShImportModels model)
        {
            if (model.FileUploads != null && model.FileUploads.ContentLength > 0)
            {
                List<SSHWareHouseDto> lstInsert = new List<SSHWareHouseDto>();
                if (model.FileUploads.FileName.EndsWith(".txt"))
                {
                    Stream stream = model.FileUploads.InputStream;
                    string m = "";
                    var xxx = new StreamReader(stream);
                    while (xxx.EndOfStream == false)
                    {
                        m = xxx.ReadLine();
                        if (!string.IsNullOrEmpty(m))
                        {
                            string[] arrayobj = m.Split('|');
                            SSHWareHouseDto obj = new SSHWareHouseDto();
                            obj.IpAddress = arrayobj[0];
                            obj.username = arrayobj[1];
                            obj.password = arrayobj[2];
                            obj.CountryCode = arrayobj[3];
                            obj.CreatedDate = DateTime.Now;
                            if (obj.CountryCode == "null")
                            {
                                obj.CountryCode = model.FileUploads.FileName.Replace(".txt", "");
                            }
                            lstInsert.Add(obj);
                        }
                    }
                    RepositoryService.SSHSystemService.InsertSShByList(lstInsert);
                }
                else
                {
                    ViewBag.ErrorMessage = "File khong dung dinh dang";
                }
            }
            return View();
        }
    }
}

WebMMO.WEB/Areas/SshManage/Views/ManageSSH/ImportSSH.cshtml
@model WebMMO.Web.Areas.SshManage.Models.SShImportModels

@{
    ViewBag.Title = "SSH Import";
}
<script>

    $(document).ready(function () {
        $.validator.setDefaults({
            ignore: []
        });
    });

    function CopyMe(oFileInput, sTargetID) {
        var arrTemp = oFileInput.value.split('\\');
        document.getElementById(sTargetID).value = arrTemp[arrTemp.length - 1];
    }

    function submitVaildate() {
        $.validator.unobtrusive.parse($('#formaction'));
        var valid = $('#formaction').valid();
        if (!valid) {
            return false;
        } else {
            $("#formaction").submit();
        }
        return false;
    };

</script>
<div class="right_col" role="main">
    <div class="content-padding">
        <div class="page-title">
            <div class="title_left">
                <h3>SSH Import</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">

                    <div class="x_content">

                        @using (Html.BeginForm("ImportSSH", "ManageSSH", new { Area = "SshManage" }, FormMethod.Post, new { id = "formaction", @class = "form-horizontal form-label-left", enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <div class="input-group">
                                        <label class="input-group-btn">
                                            <span class="btn btn-success input-sm">
                                                Browse… <input class="class_image" name="FileUploads" type="file" id="FileUploads"  style="display: none;" onchange="CopyMe(this,'inputimage')">
                                            </span>
                                        </label>
                                        <input type="text" id="inputimage" class="form-control input-sm" readonly="readonly">
                                    </div>'
                                </div>
                            </div>
                        }

                        <div class="row">
                            <div class="col-xs-12">
                                <div class="ln_solid"></div>
                                @Html.ActionLink("Quay lại quản lý", "", "ManageSSH", new { Area = "SshManage" }, new { @class = "btn btn-round btn-primary pull-left" })
                                <button type="button" id="btnSubmit" onclick="return submitVaildate();" class="btn btn-round btn-primary pull-right">
                                    Lưu
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebMMO.WEB/Areas/SshManage/Views/ManageSSH/Index.cshtml
@{
    ViewBag.Title = "Manage Images System";
}

<script type="text/javascript">

    $(document).ready(function () {

        var table = $('#resultDatabase').DataTable({
            dom: 'l<"toolbar">frtip',
            "responsive": {
                "details": true
            },
            "processing": true,
            "serverSide": true,
            "stateSave": false,
            "paging": true,
            "searching": false,
            "order": [[1, "desc"]],
            "ajax": {
                "url": "@Url.Action("ManageSSHSearch", "ManageSSH", new { Area= "SshManage" })",
                "type": "GET",
                "data": function (d) {

                },
                "dataSrc": function (res) {
                    var count = res.recordsTotal;
                    var htmlShow = 'Tổng ' + count + ' tìm thây';
                    $("#idShowTotal").text(htmlShow);
                    return res.data;
                }

            },
            "columns": [
                { "data": "Id", "orderable": false },
                { "data": "username", "orderable": false },
                { "data": "password", "orderable": false },
                { "data": "IpAddress", "orderable": false },
                { "data": "CountryCode", "orderable": false },
                { "data": "Id", "orderable": false }
            ],
            "createdRow": function (row, data, index) {

            },
            'columnDefs': [
                {
                    'targets': 0,
                    'searchable': false,
                    'orderable': false,
                    'render': function (data, type, full, meta) {
                        var idSearch = full.ID;
                        var htmlReturn = '<input type="checkbox" class="dt-body-center checkboxgroup" value="' + $('<div/>').text(idSearch).html() + '" id="cb_' + $('<div/>').text(idSearch).html() + '" onclick="SelectListID(cb_' + $('<div/>').text(idSearch).html() + ')">';
                        return htmlReturn;
                    }
                },
                {
                    targets: 5,
                    "render": function (data, type, full, meta) {

                        var htmlReturn = ' <div class="btn-group">';

                        htmlReturn = htmlReturn + '</div>';
                        return htmlReturn;
                    }
                }

            ],

            //initComplete: function () {
            //    $("div.toolbar")
            //       .html('<button type="button" id="batch_activated" class="btn btn-round btn-success" onclick="fVerifiedPlaceBatch(1)">Batch Approve</button>' +
            //            '<button type="button" id="batch_disapprove" class="btn btn-round btn-danger" onclick="fVerifiedPlaceBatch(0)">Batch Disapprove</button>');
            //}

        });

        $('#btnSubmit').click(function () {

            table.draw();
            //table.ajax.reload(null, false);
            return false;
        });
    });

</script>

<div class="right_col" role="main">
    <div class="content-padding">
        <div class="page-title">
            <div class="title_left">
                <h3>Quản lý SSH</h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top-main-button">
                    <div class="input-group">
                        @Html.ActionLink("Import SSH", "ImportSSH", "ManageSSH", new { Area = "SshManage" }, new { @class = "btn btn-round btn-primary" })
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix">
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Tìm kiếm</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        </ul>
                        <div class="clearfix">
                        </div>
                    </div>
                    <div class="x_content">

                        <div class="row">
                            <div class="col-xs-12">
                                <div class="ln_solid">
                                </div>
                                <input id="btnSubmit" type="submit" value="Tìm kiếm" class="btn btn-round btn-primary pull-right" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>
                            Kết quả <small id="idShowTotal"></small>
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        </ul>
                        <div class="clearfix">
                        </div>
                    </div>
                    <div class="x_content">
                        <table id="resultDatabase" class="table table-striped table-bordered dt-responsive nowrap"
                               cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" onclick="CheckAll(this.value)" class="dt-body-center" id="cb_All" />
                                    </th>
                                    <th>
                                        username
                                    </th>
                                    <th>
                                        password
                                    </th>
                                    <th>
                                        ip address
                                    </th>
                                    <th>
                                        country code
                                    </th>

                                    <th class="text-center">
                                        Thao tác
                                    </th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="dvQuestionModal" tabindex="-1" role="dialog" aria-hidden="true"
     data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="dvTitleShow"></h4>
            </div>
            <div class="modal-body">
                <div>
                    <div class="row text-center" id="idRemarks">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="btnSubmitDisApprolval" class="btn btn-primary">Confirm</button>
            </div>
        </div>
    </div>
</div>